
# Global Config
debug: False
task: 'regression' #['regression', 'classification']

# directory setting
input_dir_root: './input/'
input_dir_root_jn: '../input/'
input_dir: './src/input/'
input_dir_jn: '../src/input/'
output_dir: './src/output/'
output_dir_jn: '../src/output/'
output_dir_fold: '../src/input/' # ['./src/input/', '../src/input/']
output_dir_pp: '../src/input/' # ['./src/input/', '../src/input/']
output_dir_cv: './src/output/'

# file name setting
fname_submission: 'submission.csv'
fname_log_fold: 'log_fold'
fname_log_pp: 'log_pp'
fname_log_cv: 'log_cv'
fname_importance: 'feature_importance.png'
fname_cm: 'cm.png'
cm_class: ['0', '1'] # binary:['0', '1'], multiclass: ['0', '1', '2',...]

# dataset setting
id: 'object_id'
target: 'likes'

# seed setting
seed: 1996

# cross validation setting
num_folds: 5
split_type: 'group' # ['kfold', 'stratified', 'group', 'stratified_group']
split_group: 'art_series_id'
split_target: 'likes'
shuffle: False

# modeling setting
model: 'lgbm' # ['lgbm', 'xgb', 'catb']
num_class: 1 # binary:1, multiclass:3, 4,...
num_seed: 1 # random seed averaging

# additional setting
do_log_scale: True # regression: scaling target with log1p
cat_negative_value: True # cat negative value
do_weight: False # target weight for imbalance classification
custom_eval: null # custom objective function
feval: null # custom objective function
optim_th: False # optimize threshold for discrete metric